Program('../bin/TcpServer', 'TcpServerTest.cpp',
        LIBPATH = ['../lib'],
        CPPPATH = ['.', '../',  '../utils', '../base'],
        LIBS = ['fasutils', 'fas', 'glog', 'jsoncpp', 'pthread'],
        CCFLAGS = ['-Wall', '-static', '-std=c++11']
        )
Program('../bin/JsonTest', 'JsonTest.cpp',
        LIBPATH = ['../lib'],
        CPPPATH = ['.', '..', '../utils', '../base'],
        LIBS = ['fasutils', 'fas', 'glog', 'jsoncpp', 'pthread'],
        CCFLAGS = ['-Wall', '-static', '-std=c++11']
        )
